"use client";

import Alert from "@mui/material/Alert";
import Button from "@mui/material/Button";
import Chip from "@mui/material/Chip";
import Paper from "@mui/material/Paper";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import { useState } from "react";
import { enhanceListingDescription } from "@/lib/api/ai";
import type { Amenity, AvailabilityStatus, HouseType } from "@/types/domain";

type AiDescriptionAssistProps = {
  title: string;
  description: string;
  city: string;
  area: string;
  houseType: HouseType;
  bedrooms: number;
  bathrooms: number;
  availabilityStatus: AvailabilityStatus;
  furnished: boolean;
  rentAmount: number;
  selectedAmenityIds: string[];
  amenities: Amenity[];
  onApply: (nextDescription: string) => void;
};

export function AiDescriptionAssist({
  title,
  description,
  city,
  area,
  houseType,
  bedrooms,
  bathrooms,
  availabilityStatus,
  furnished,
  rentAmount,
  selectedAmenityIds,
  amenities,
  onApply,
}: AiDescriptionAssistProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [result, setResult] = useState<{
    enhancedDescription: string;
    suggestions: string[];
    provider: string;
  } | null>(null);

  async function handleGenerate() {
    setIsLoading(true);
    setErrorMessage(null);

    try {
      const amenityNames = amenities
        .filter((amenity) => selectedAmenityIds.includes(amenity.id))
        .map((amenity) => amenity.name);

      const response = await enhanceListingDescription({
        title,
        description,
        city,
        area,
        houseType,
        bedrooms,
        bathrooms,
        availabilityStatus,
        furnished,
        rentAmount,
        amenities: amenityNames,
      });

      setResult(response);
    } catch (error) {
      const message =
        error instanceof Error
          ? error.message
          : "Failed to generate AI suggestion.";
      setErrorMessage(message);
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <Paper sx={{ p: 3 }}>
      <Stack spacing={2}>
        <Stack spacing={1}>
          <Chip
            label="AI Assist"
            color="secondary"
            sx={{ width: "fit-content" }}
          />
          <Typography variant="h5">Enhance description</Typography>
          <Typography color="text.secondary">
            Generate a stronger draft from your current listing details. The
            result is always editable before save.
          </Typography>
        </Stack>

        {errorMessage ? <Alert severity="error">{errorMessage}</Alert> : null}

        <Stack direction="row">
          <Button
            type="button"
            variant="outlined"
            onClick={handleGenerate}
            disabled={
              isLoading ||
              !title.trim() ||
              !description.trim() ||
              !city.trim() ||
              !area.trim()
            }
          >
            {isLoading ? "Generating..." : "Generate AI suggestion"}
          </Button>
        </Stack>

        {result ? (
          <Stack spacing={1.5}>
            <Alert severity="info">
              Generated by `{result.provider}`. Review and edit before saving
              the listing.
            </Alert>
            <Paper variant="outlined" sx={{ p: 2 }}>
              <Typography
                color="text.secondary"
                sx={{ whiteSpace: "pre-wrap" }}
              >
                {result.enhancedDescription}
              </Typography>
            </Paper>
            <Stack spacing={0.75}>
              <Typography fontWeight={700}>Suggestions</Typography>
              {result.suggestions.map((suggestion) => (
                <Typography key={suggestion} color="text.secondary">
                  - {suggestion}
                </Typography>
              ))}
            </Stack>
            <Stack direction="row">
              <Button
                type="button"
                variant="contained"
                onClick={() => onApply(result.enhancedDescription)}
              >
                Use this description
              </Button>
            </Stack>
          </Stack>
        ) : null}
      </Stack>
    </Paper>
  );
}
